import type { GameModule } from '../types';

export const gameModules: GameModule[] = [
  {
    id: 'quiz',
    name: 'Quick-Fire Quiz',
    description: 'Test your knowledge with rapid-fire questions',
    icon: 'Zap',
    route: '/game/quiz',
    winCondition: '≥80% correct in 10 questions',
    hasTimer: true,
  },
  {
    id: 'flashcards',
    name: 'Flashcards',
    description: 'Master key concepts with spaced repetition',
    icon: 'Clock',
    route: '/game/flashcards',
    winCondition: 'Complete 2 cycles successfully',
    hasTimer: false,
  },
  {
    id: 'case',
    name: 'Case Builder',
    description: 'Solve real marketing challenges',
    icon: 'Building',
    route: '/game/case',
    winCondition: 'Average score ≥4/5',
    hasTimer: false,
  },
  {
    id: 'matching',
    name: 'Matching Matrix',
    description: 'Connect metrics with their definitions',
    icon: 'Target',
    route: '/game/matching',
    winCondition: 'Match all pairs correctly',
    hasTimer: true,
  },
  {
    id: 'acronym',
    name: 'Acronym Sprint',
    description: 'Expand marketing acronyms at lightning speed',
    icon: 'Search',
    route: '/game/acronym',
    winCondition: '15 correct in 90 seconds',
    hasTimer: true,
  },
  {
    id: 'trends',
    name: 'Industry Trends',
    description: 'Stay current with 2024 marketing developments',
    icon: 'TrendingUp',
    route: '/game/trends',
    winCondition: '≥80% correct on current trends',
    hasTimer: true,
  },
  {
    id: 'agilite-quiz',
    name: 'Agilite Company Quiz',
    description: 'Master everything about Agilite tactical gear company',
    icon: 'Target',
    route: '/game/agilite-quiz',
    winCondition: '≥80% correct on company knowledge',
    hasTimer: true,
  },
  {
    id: 'agilite-scenarios',
    name: 'Agilite Business Scenarios',
    description: 'Analyze real-world business challenges at Agilite',
    icon: 'Users',
    route: '/game/agilite-scenarios',
    winCondition: 'Complete all scenario analyses',
    hasTimer: false,
  }
]; 